version: 0.0
os: linux

files:
  - source: app.war
    destination: /opt/tomcat/webapps/

hooks:
  BeforeInstall:
    - location: scripts/stop_tomcat.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/start_tomcat.sh
      timeout: 60
      runas: root
